name: Test and Release Go CLI

on:
  push:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
      - run: go version
      - name: Execute the tests
        run: go test -race ./...

  release:
    needs: tests
    name: GoReleaser Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
      - run: go version
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
